# Hyper Params
LEARNING_RATE = 0.00025
BATCH_SIZE = 30


GAMMA = 0.8
EPSILON_START = 0.5
EPSILON_CHANGE_RATE = 1e-5
MINIMUM_EPSILON = 0.05
INPUT_SHAPE = (84, 84, 4)       # in_height, in_width, in_channels


TRAINING_FREQUENCY = 20
REPLAY_MEMORY_LENGTH = 1e6
REPLAY_START_LENGTH = 1e3
